### ISSUE TITLE
Run Error for Sanity Checks

### ISSUE THREAD

**Issue by funky81** [funky81/installrhel#1]
Based on installrhel on Openshift 3.11 : [sanity check error](https://github.com/gshipley/installrhel/issues/2)

**Comment by funky81** [comment]
#https://github.com/gshipley/installrhel/issues/2

**Comment by funky81** [comment]
fix by pull this PR : https://github.com/funky81/installrhel/pull/2

**Comment by jhonjcastroh** [comment]
Replace for:

openshift_node_groups=[{'name': 'node-config-all-in-one', 'labels': ['node-role.kubernetes.io/master=true', 'node-role.kubernetes.io/infra=true', 'node-role.kubernetes.io/compute=true'], 'edits': [{ 'key': 'kubeletArguments.pods-per-core','value': ['NUMBER_OF_PODS']}]}]
